\input texinfo
@comment             **********************************************************
@setfilename         g100
@settitle            The Guile 100 Programs Project
@comment
@set utfversion      0.6
@set utfversiondate  Apr 22, 2013
@comment
@comment             This is a Texinfo file.  To convert it to Info hypertext
@comment             format, you will need the `makeinfo' program from the GNU
@comment             Texinfo package.  To produce a PDF, use `texi2pdf'. 
@comment             
@comment             
@comment             **********************************************************

@comment HISTORY:
@comment
@comment * Mar 11, 2013: initial commit.

@dircategory The Algorithmic Language Scheme
@direntry
* G100: (g100). The Guile 100 Programs Project
@end direntry

@macro newterm{term}
@cindex \term\
@dfn{\term\}
@end macro

@ifhtml
@macro css{classname, text}
@inlineraw{html, <span class="\classname\">\text\<span>}
@end macro
@end ifhtml

@ifnothtml
@macro css{classname, text}
\text\
@end macro
@end ifnothtml


@c @setchapternewpage odd
@setshortcontentsaftertitlepage

@titlepage
@title  The Guile 100 Programs Project
@subtitle @value{utfversion} - @value{utfversiondate}
@author Edited by Michael Gran

@page
@vskip 0pt plus 1filll
@noindent
@copyright{} 2013 by Michael Gran

@noindent
100 Guile Programs

@noindent
This work is licensed under GFDL 1.3+@*
(@url{http://www.gnu.org/licenses/fdl.html, GFDL 1.3+}).

@noindent
A Lonely Cactus Production@*
Los Angeles, California 


@end titlepage
@everyheading @| @| @thispage

@c to suppress the black boxes after overfull lines:
@finalout

@node Top, Preface, (dir), (dir)

@ifinfo

@heading The Guile 100 Programs Project

@noindent
Edited by Michael Gran@*
@copyright{} 2013 Michael Gran

@noindent
Version @value{utfversion} (@value{utfversiondate})

@end ifinfo

@ifhtml

@heading The Guile 100 Programs Project

@noindent
Version @value{utfversion} (@value{utfversiondate})

This online resource is a collection of sample programs written in GNU
Guile, an implementation of the Scheme language.

@end ifhtml

@menu
* Preface::                     
* Acknowledgements::            
* Theme 1::                     
* Theme 2::                     
* References::                  
* Index::                       

@detailmenu
 --- The Detailed Node Listing ---

Theme 1: ``/bin''

* Problem 1::                   echo and cat
* Problem 2::                   ls
* Problem 3::                   LZW Compression
* Problem 4::                   tar file archives

Theme 2: Web 1.0

* Problem 5::                   PHP-Style GUILE
* Problem 6::                   CGI and MySQL

@end detailmenu
@end menu

@include preface.texi
@include acknowledgements.texi
@include ch01_bin.texi
@include ch02_web1.texi
@include references.texi
@include index.texi

@bye
